#!/bin/bash
# Salt Stack install in Debian

sudo apt install -y lsb-release
wget -O - https://repo.saltstack.com/apt/debian/9/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
echo "deb http://repo.saltstack.com/apt/debian/9/amd64/latest stretch main" > /etc/apt/sources.list.d/saltstack.list
sudo apt-get update
sudo apt-get install salt-minion

#sudo apt-get install salt-master
#sudo apt-get install salt-ssh
#sudo apt-get install salt-syndic
#sudo apt-get install salt-cloud
#sudo apt-get install salt-api
